% Setup meta-data of your project
\newcommand{\mytitle}{Your Title}
\newcommand{\mylastname}{Lastname}
\newcommand{\myfirstname}{Firstname}
\newcommand{\myemail}{my.email@graduateinstitute.ch}
\newcommand{\mydepartment}{Your Department}
\newcommand{\myprogramme}{MA/PhD in \mydepartment}
\newcommand{\mythesisno}{99999} % provided by PhD secretariat
\newcommand{\mykeywords}{your, keywords} % only used for PDF metadata
\newcommand{\mysubject}{Your Subject} % only used for PDF metadata